version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  apt_packages:
    - plantuml

sphinx:
  configuration: docs/conf.py

python:
  install:
    - path: .
    - requirements: docs/requirements.txt